# Generated by Django 2.1.4 on 2019-01-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=500)),
                ('release_date', models.DateTimeField()),
                ('album_popularity', models.CharField(max_length=50)),
                ('album_explicit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('artist_followers', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('playlist_name', models.TextField(max_length=100)),
                ('playlist_url', models.CharField(max_length=1000)),
                ('playlist_num_tracks', models.IntegerField(null=True)),
                ('playlist_featured', models.BooleanField(default=False)),
                ('playlist_owner', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('song_name', models.TextField()),
                ('artist_name', models.CharField(max_length=120)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_app.Artist')),
            ],
        ),
    ]
