# Generated by Django 2.1.4 on 2019-01-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('playlist_name', models.TextField(max_length=100)),
                ('playlist_url', models.CharField(max_length=1000)),
                ('playlist_num_tracks', models.IntegerField(null=True)),
                ('playlist_featured', models.BooleanField(default=False)),
                ('playlist_owner', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('song_name', models.TextField()),
                ('artist_name', models.CharField(max_length=120)),
                ('song_is_explicit', models.BooleanField()),
                ('song_popularity', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('song_duration_ms', models.IntegerField()),
                ('recommended_user', models.CharField(max_length=500)),
            ],
        ),
    ]
