# Generated by Django 2.1.4 on 2019-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_featured',
            field=models.BooleanField(default=False),
        ),
    ]
