# Generated by Django 2.1.4 on 2019-01-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_created',
            field=models.CharField(default='No date', max_length=500),
        ),
        migrations.AddField(
            model_name='song',
            name='date_created',
            field=models.CharField(default='No date', max_length=500),
        ),
    ]
