# Generated by Django 2.1.4 on 2018-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_num_tracks',
            field=models.IntegerField(null=True),
        ),
    ]
