# Generated by Django 2.1.4 on 2019-01-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_followers',
            field=models.IntegerField(),
        ),
    ]
