# Generated by Django 2.1.4 on 2019-01-27 22:11

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_auto_20190127_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recprofile',
            name='user_hdbscan',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
    ]
