# Generated by Django 2.1.4 on 2019-02-09 22:30

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_auto_20190127_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='recprofile',
            name='user_pca_obj',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
    ]
