# Generated by Django 2.1.4 on 2019-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_auto_20190113_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_cover_art',
            field=models.CharField(default='no_img', max_length=5000, null=True),
        ),
    ]
