# Generated by Django 2.1.4 on 2019-01-13 19:02

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_auto_20190113_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_df_features_obj',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_pca_obj',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_top_clusters_obj',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
    ]
