# Generated by Django 2.1.4 on 2019-01-13 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_app', '0007_profile_user_has_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='RecProfile',
        ),
    ]
