# Generated by Django 2.1.4 on 2019-01-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0008_auto_20190113_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recprofile',
            name='user_pca_obj',
        ),
    ]
