# Generated by Django 2.1.4 on 2019-01-27 18:44

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0009_remove_recprofile_user_pca_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='recprofile',
            name='user_df_scaled_obj',
            field=picklefield.fields.PickledObjectField(default='no_object_yet', editable=False, null=True),
        ),
    ]
